# Project configuration
name: "KoboToolbox"
shortdescription: "Data Collection Tools for Challenging Environments"
description: "KoboToolbox is a suite of tools for field data collection for use in challenging environments. Our software is free and open source. Most of our users are people working in humanitarian crises, as well as aid professionals and researchers working in developing countries."
baseurl: "https://kobotoolbox.github.io/kobotoolbox-org-v2" # TEMPORARY URL FOR TESTING

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 5
paginate_path: "/blog/page:num/"
permalink: /blog/:title

# used for Open Graph (i.e. social sharing)
default_og_image: "/assets/images/common/kobotoolbox_opengraph_image.png"
default_thumbnail: "/assets/images/site/blog_post_default.png"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "blog-post"
  -
    scope:
      path: "_jobs"
    values:
      layout: "job"

collections:
  jobs:
    output: true
    permalink: /join-our-team/:name

destination: docs

# Jekyll configuration
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
  auto_ids: true
timezone: US/Eastern
port: 2038 # Used for development
exclude:
  - .parcel-cache
  - .editorconfig
  - .eslintrc.js
  - .prettierrc.js
  - .stylelintrc.js
  - node_modules
  - README.md
  - package.json
  - package-lock.json
  - "*.sublime-project"
  - Gemfile
  - Gemfile.lock
