name: "KoBoToolbox"
shortdescription: "Data Collection Tools for Challenging Environments"
description: "KoBoToolbox is a suite of tools for field data collection for use in challenging environments. Our software is free and open source. Most of our users are people working in humanitarian crises, as well as aid professionals and researchers working in developing countries."
baseurl: "https://www.kobotoolbox.org"

# site configuration
safe: true
quiet: false
future: true
encoding: utf-8
markdown: kramdown
kramdown:
  auto_ids: false
timezone: US/Eastern
port: 2038 # 0 to 65535
exclude:
  - node_modules
  - README.md
  - package.json
  - package-lock.json
permalink: /blog/:title
sass:
  sass_dir: _scss
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "blog-post"
# this flag manages the visibility of blog, i.e. it hides blog link from top
# navigation and blog section from main page
isBlogEnabled: false

# used for Open Graph (i.e. social sharing)
default_og_image: "/images/kobotoolbox_opengraph_image.png"

# FundraiseUp stuff
fundraiseup_js_id: "ASAUFVGL"
fundraiseup_html_id: "XESYHRGF"
