# This workflow builds live website into /docs for GH pages

name: CI

on:
  push:
    branches: [ main ]

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Copy some assets
        run: npm run copy-files

      - name: Build assets
        run: npm run assets-build
